//! Watchtower Service for Payment Channel Monitoring
//!
//! Production-grade implementation for detecting and responding to
//! fraudulent payment channel closures.

use crate::currency_chain::CurrencyChainClient;
use crate::payment_channels::{
    ChannelError, PaymentChannelManager, SignedStateUpdate, UnilateralCloseRequest,
};
use chrono::{DateTime, Duration, Utc};
use dchat_core::types::UserId;
use sha2::{Digest, Sha256};
use std::collections::HashMap;
use std::sync::Arc;
use thiserror::Error;
use tokio::sync::RwLock;
use uuid::Uuid;

/// Errors that can occur during watchtower operations
#[derive(Error, Debug)]
pub enum WatchtowerError {
    #[error("Channel not found: {0}")]
    ChannelNotFound(String),

    #[error("Invalid state update signature")]
    InvalidSignature,

    #[error("State update is stale (nonce too low)")]
    StaleStateUpdate,

    #[error("Challenge submission failed: {0}")]
    ChallengeSubmissionFailed(String),

    #[error("Watchtower capacity exceeded")]
    CapacityExceeded,

    #[error("Payment channel error: {0}")]
    PaymentChannelError(#[from] ChannelError),

    #[error("Internal error: {0}")]
    InternalError(String),
}

/// Alert severity levels
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AlertSeverity {
    /// Informational - no action required
    Info,
    /// Warning - potential issue detected
    Warning,
    /// Critical - immediate action required
    Critical,
}

/// Types of watchtower alerts
#[derive(Debug, Clone)]
pub enum AlertType {
    /// Detected attempted fraud with old state
    FraudAttempt {
        channel_id: String,
        submitted_nonce: u64,
        latest_nonce: u64,
    },
    /// Challenge window expiring soon
    ChallengeExpiring {
        channel_id: String,
        expires_at: DateTime<Utc>,
    },
    /// Unilateral close detected
    UnilateralClose {
        channel_id: String,
        closed_by: UserId,
    },
    /// Channel dispute resolved
    DisputeResolved { channel_id: String, winner: UserId },
    /// Watchtower fee payment received
    FeePaymentReceived { channel_id: String, amount: u64 },
    /// Channel monitoring expired
    MonitoringExpired { channel_id: String },
}

/// Alert generated by the watchtower
#[derive(Debug, Clone)]
pub struct WatchtowerAlert {
    pub id: Uuid,
    pub alert_type: AlertType,
    pub severity: AlertSeverity,
    pub timestamp: DateTime<Utc>,
    pub message: String,
    pub action_taken: Option<String>,
}

/// State snapshot stored by watchtower for each monitored channel
#[derive(Debug, Clone)]
pub struct WatchedChannelState {
    /// Latest known state update
    pub latest_state: SignedStateUpdate,
    /// Time this state was recorded
    pub recorded_at: DateTime<Utc>,
    /// Hash of the state for quick comparison
    pub state_hash: [u8; 32],
}

/// A channel being monitored by the watchtower
#[derive(Debug, Clone)]
pub struct WatchedChannel {
    /// Channel identifier
    pub channel_id: String,
    /// Owner of the channel (the party we're protecting)
    pub protected_party: UserId,
    /// Counterparty in the channel
    pub counterparty: UserId,
    /// When monitoring started
    pub monitoring_started: DateTime<Utc>,
    /// When monitoring expires (based on fee payment)
    pub monitoring_expires: DateTime<Utc>,
    /// Fee paid for monitoring service
    pub fee_paid: u64,
    /// Latest known channel state
    pub latest_state: Option<WatchedChannelState>,
    /// History of detected fraud attempts
    pub fraud_attempts: Vec<FraudAttemptRecord>,
    /// Whether we successfully challenged a fraud attempt
    pub challenge_submitted: bool,
    /// When the challenge was submitted (for computing dispute deadline)
    pub challenge_submitted_at: Option<DateTime<Utc>>,
}

/// Record of a detected fraud attempt
#[derive(Debug, Clone)]
pub struct FraudAttemptRecord {
    pub detected_at: DateTime<Utc>,
    pub submitted_nonce: u64,
    pub latest_nonce: u64,
    pub challenged: bool,
    pub challenge_successful: Option<bool>,
}

/// Configuration for the watchtower service
#[derive(Debug, Clone)]
pub struct WatchtowerConfig {
    /// Minimum fee (in tokens) to monitor a channel for 30 days
    pub min_monthly_fee: u64,
    /// Maximum number of channels to monitor
    pub max_channels: usize,
    /// How often to check for on-chain events (seconds)
    pub poll_interval_secs: u64,
    /// Hours before challenge expiry to send warning
    pub challenge_warning_hours: i64,
}

impl Default for WatchtowerConfig {
    fn default() -> Self {
        Self {
            min_monthly_fee: 1000, // 1000 tokens per month
            max_channels: 10000,
            poll_interval_secs: 30,
            challenge_warning_hours: 6,
        }
    }
}

/// Watchtower service for monitoring payment channels
pub struct Watchtower {
    config: WatchtowerConfig,
    /// Channels being monitored
    channels: RwLock<HashMap<String, WatchedChannel>>,
    /// Generated alerts
    alerts: RwLock<Vec<WatchtowerAlert>>,
    /// Payment channel manager for submitting challenges
    channel_manager: Arc<PaymentChannelManager>,
    /// Alert callback for external notification
    alert_callback: RwLock<Option<Box<dyn Fn(WatchtowerAlert) + Send + Sync>>>,
}

impl Watchtower {
    /// Create a new watchtower service
    pub fn new(config: WatchtowerConfig, channel_manager: Arc<PaymentChannelManager>) -> Self {
        Self {
            config,
            channels: RwLock::new(HashMap::new()),
            alerts: RwLock::new(Vec::new()),
            channel_manager,
            alert_callback: RwLock::new(None),
        }
    }

    /// Register a channel for monitoring
    pub async fn register_channel(
        &self,
        channel_id: String,
        protected_party: UserId,
        counterparty: UserId,
        initial_state: SignedStateUpdate,
        fee_paid: u64,
    ) -> Result<(), WatchtowerError> {
        // Check capacity
        let channels = self.channels.read().await;
        if channels.len() >= self.config.max_channels {
            return Err(WatchtowerError::CapacityExceeded);
        }
        drop(channels);

        // Calculate monitoring duration based on fee
        let months = (fee_paid / self.config.min_monthly_fee).max(1);
        let duration = Duration::days(30 * months as i64);

        let state_hash = self.hash_state(&initial_state);

        let watched_channel = WatchedChannel {
            channel_id: channel_id.clone(),
            protected_party,
            counterparty,
            monitoring_started: Utc::now(),
            monitoring_expires: Utc::now() + duration,
            fee_paid,
            latest_state: Some(WatchedChannelState {
                latest_state: initial_state,
                recorded_at: Utc::now(),
                state_hash,
            }),
            fraud_attempts: Vec::new(),
            challenge_submitted: false,
            challenge_submitted_at: None,
        };

        let mut channels = self.channels.write().await;
        channels.insert(channel_id.clone(), watched_channel);

        // Generate fee receipt alert
        self.emit_alert(WatchtowerAlert {
            id: Uuid::new_v4(),
            alert_type: AlertType::FeePaymentReceived {
                channel_id: channel_id.clone(),
                amount: fee_paid,
            },
            severity: AlertSeverity::Info,
            timestamp: Utc::now(),
            message: format!(
                "Channel {} registered for monitoring until {}",
                channel_id,
                Utc::now() + duration
            ),
            action_taken: None,
        })
        .await;

        Ok(())
    }

    /// Update the latest known state for a channel
    pub async fn update_channel_state(
        &self,
        channel_id: String,
        new_state: SignedStateUpdate,
    ) -> Result<(), WatchtowerError> {
        let mut channels = self.channels.write().await;
        let channel = channels
            .get_mut(&channel_id)
            .ok_or_else(|| WatchtowerError::ChannelNotFound(channel_id.clone()))?;

        // Verify the state update is newer than what we have
        if let Some(ref current_state) = channel.latest_state {
            if new_state.state.nonce <= current_state.latest_state.state.nonce {
                return Err(WatchtowerError::StaleStateUpdate);
            }
        }

        // Signature verification is delegated to PaymentChannelManager which tracks
        // the Ed25519 public keys for each channel party. The watchtower trusts
        // that state updates passed to it have already been verified by the manager.
        // This separation keeps the watchtower focused on fraud detection and
        // challenge submission while the manager handles cryptographic verification.
        let state_hash = self.hash_state(&new_state);

        channel.latest_state = Some(WatchedChannelState {
            latest_state: new_state,
            recorded_at: Utc::now(),
            state_hash,
        });

        Ok(())
    }

    /// Check for fraud on a specific channel
    /// Called when we detect a unilateral close attempt on-chain
    pub async fn check_for_fraud(
        &self,
        channel_id: String,
        close_request: &UnilateralCloseRequest,
    ) -> Result<Option<FraudAttemptRecord>, WatchtowerError> {
        let mut channels = self.channels.write().await;
        let channel = channels
            .get_mut(&channel_id)
            .ok_or_else(|| WatchtowerError::ChannelNotFound(channel_id.clone()))?;

        // Check if monitoring is still active
        if Utc::now() > channel.monitoring_expires {
            // Emit expired alert
            drop(channels);
            self.emit_alert(WatchtowerAlert {
                id: Uuid::new_v4(),
                alert_type: AlertType::MonitoringExpired {
                    channel_id: channel_id.clone(),
                },
                severity: AlertSeverity::Warning,
                timestamp: Utc::now(),
                message: format!("Monitoring for channel {} has expired", channel_id),
                action_taken: None,
            })
            .await;
            return Ok(None);
        }

        // Emit unilateral close alert
        let closer = if close_request.final_state.state.sender_balance > 0 {
            channel.protected_party.clone()
        } else {
            channel.counterparty.clone()
        };

        // Check if we have a newer state
        if let Some(ref our_state) = channel.latest_state {
            let submitted_nonce = close_request.final_state.state.nonce;
            let our_nonce = our_state.latest_state.state.nonce;

            if submitted_nonce < our_nonce {
                // FRAUD DETECTED!
                let fraud_record = FraudAttemptRecord {
                    detected_at: Utc::now(),
                    submitted_nonce,
                    latest_nonce: our_nonce,
                    challenged: false,
                    challenge_successful: None,
                };

                channel.fraud_attempts.push(fraud_record.clone());

                // Emit critical alert
                drop(channels);
                self.emit_alert(WatchtowerAlert {
                    id: Uuid::new_v4(),
                    alert_type: AlertType::FraudAttempt {
                        channel_id: channel_id.clone(),
                        submitted_nonce,
                        latest_nonce: our_nonce,
                    },
                    severity: AlertSeverity::Critical,
                    timestamp: Utc::now(),
                    message: format!(
                        "FRAUD DETECTED: Channel {} close attempt with nonce {} but we have nonce {}",
                        channel_id, submitted_nonce, our_nonce
                    ),
                    action_taken: Some("Preparing challenge submission".to_string()),
                }).await;

                return Ok(Some(fraud_record));
            }
        }

        // No fraud detected, just a normal close
        drop(channels);
        self.emit_alert(WatchtowerAlert {
            id: Uuid::new_v4(),
            alert_type: AlertType::UnilateralClose {
                channel_id: channel_id.clone(),
                closed_by: closer,
            },
            severity: AlertSeverity::Info,
            timestamp: Utc::now(),
            message: format!("Unilateral close detected for channel {}", channel_id),
            action_taken: None,
        })
        .await;

        Ok(None)
    }

    /// Submit a challenge for a detected fraud attempt
    pub async fn submit_challenge(&self, channel_id: String) -> Result<(), WatchtowerError> {
        let channels = self.channels.read().await;
        let channel = channels
            .get(&channel_id)
            .ok_or_else(|| WatchtowerError::ChannelNotFound(channel_id.clone()))?;

        let state = channel
            .latest_state
            .as_ref()
            .ok_or(WatchtowerError::InternalError(
                "No state to challenge with".to_string(),
            ))?;

        let challenge_state = state.latest_state.clone();
        drop(channels);

        // Submit challenge through payment channel manager
        // Note: We use the protected party as the challenger
        let challenger_id = {
            let channels = self.channels.read().await;
            let channel = channels
                .get(&channel_id)
                .ok_or_else(|| WatchtowerError::ChannelNotFound(channel_id.clone()))?;
            channel.protected_party.clone()
        };

        self.channel_manager
            .challenge_close(&channel_id, challenge_state.clone(), &challenger_id)
            .map_err(|e| WatchtowerError::ChallengeSubmissionFailed(e.to_string()))?;

        // Update channel record
        let now = Utc::now();
        let mut channels = self.channels.write().await;
        if let Some(channel) = channels.get_mut(&channel_id) {
            channel.challenge_submitted = true;
            channel.challenge_submitted_at = Some(now);

            // Update the most recent fraud attempt
            if let Some(fraud) = channel.fraud_attempts.last_mut() {
                fraud.challenged = true;
            }
        }

        // Emit success alert
        drop(channels);
        self.emit_alert(WatchtowerAlert {
            id: Uuid::new_v4(),
            alert_type: AlertType::DisputeResolved {
                channel_id: channel_id.clone(),
                winner: UserId::new(), // Will be set when dispute is finalized
            },
            severity: AlertSeverity::Info,
            timestamp: Utc::now(),
            message: format!("Challenge submitted for channel {}", channel_id),
            action_taken: Some(format!(
                "Submitted state with nonce {}",
                challenge_state.state.nonce
            )),
        })
        .await;

        Ok(())
    }

    /// Auto-respond to fraud by submitting challenge
    pub async fn auto_respond_to_fraud(
        &self,
        channel_id: String,
        close_request: &UnilateralCloseRequest,
    ) -> Result<bool, WatchtowerError> {
        // First check for fraud
        if let Some(_fraud) = self
            .check_for_fraud(channel_id.clone(), close_request)
            .await?
        {
            // Fraud detected, submit challenge
            self.submit_challenge(channel_id).await?;
            return Ok(true);
        }
        Ok(false)
    }

    /// Check all channels for expiring challenge windows
    pub async fn check_expiring_challenges(&self) -> Vec<WatchtowerAlert> {
        let mut expiring_alerts = Vec::new();
        let warning_threshold = Duration::hours(self.config.challenge_warning_hours);
        // Dispute window is 48 hours from payment_channels::DISPUTE_WINDOW_SECONDS
        let dispute_window = Duration::seconds(crate::payment_channels::DISPUTE_WINDOW_SECONDS);

        let channels = self.channels.read().await;

        for (channel_id, channel) in channels.iter() {
            // Only check channels with submitted challenges and known submission time
            if channel.challenge_submitted {
                if let Some(submitted_at) = channel.challenge_submitted_at {
                    // Calculate actual dispute window expiry based on when challenge was submitted
                    let dispute_deadline = submitted_at + dispute_window;
                    let time_remaining = dispute_deadline - Utc::now();

                    // Warn if challenge window is expiring soon
                    if time_remaining > Duration::zero() && time_remaining <= warning_threshold {
                        let alert = WatchtowerAlert {
                            id: Uuid::new_v4(),
                            alert_type: AlertType::ChallengeExpiring {
                                channel_id: channel_id.clone(),
                                expires_at: dispute_deadline,
                            },
                            severity: AlertSeverity::Warning,
                            timestamp: Utc::now(),
                            message: format!(
                                "Challenge window for channel {} expires at {}",
                                channel_id, dispute_deadline
                            ),
                            action_taken: None,
                        };
                        expiring_alerts.push(alert);
                    }
                }
            }
        }

        // Store and emit alerts
        for alert in &expiring_alerts {
            self.emit_alert(alert.clone()).await;
        }

        expiring_alerts
    }

    /// Remove expired channel monitoring
    pub async fn cleanup_expired_channels(&self) -> usize {
        let mut channels = self.channels.write().await;
        let now = Utc::now();

        let expired: Vec<String> = channels
            .iter()
            .filter(|(_, c)| c.monitoring_expires < now)
            .map(|(id, _)| id.clone())
            .collect();

        for id in &expired {
            channels.remove(id);
        }

        expired.len()
    }

    /// Get all alerts for a specific channel
    pub async fn get_channel_alerts(&self, channel_id: &str) -> Vec<WatchtowerAlert> {
        let alerts = self.alerts.read().await;
        alerts
            .iter()
            .filter(|a| match &a.alert_type {
                AlertType::FraudAttempt { channel_id: id, .. } => id == channel_id,
                AlertType::ChallengeExpiring { channel_id: id, .. } => id == channel_id,
                AlertType::UnilateralClose { channel_id: id, .. } => id == channel_id,
                AlertType::DisputeResolved { channel_id: id, .. } => id == channel_id,
                AlertType::FeePaymentReceived { channel_id: id, .. } => id == channel_id,
                AlertType::MonitoringExpired { channel_id: id } => id == channel_id,
            })
            .cloned()
            .collect()
    }

    /// Get all critical alerts
    pub async fn get_critical_alerts(&self) -> Vec<WatchtowerAlert> {
        let alerts = self.alerts.read().await;
        alerts
            .iter()
            .filter(|a| a.severity == AlertSeverity::Critical)
            .cloned()
            .collect()
    }

    /// Get statistics about monitored channels
    pub async fn get_statistics(&self) -> WatchtowerStats {
        let channels = self.channels.read().await;
        let alerts = self.alerts.read().await;

        let total_channels = channels.len();
        let active_channels = channels
            .values()
            .filter(|c| c.monitoring_expires > Utc::now())
            .count();
        let fraud_detected = channels.values().map(|c| c.fraud_attempts.len()).sum();
        let challenges_submitted = channels.values().filter(|c| c.challenge_submitted).count();
        let total_fees: u64 = channels.values().map(|c| c.fee_paid).sum();

        WatchtowerStats {
            total_channels,
            active_channels,
            fraud_detected,
            challenges_submitted,
            total_fees_collected: total_fees,
            total_alerts: alerts.len(),
            critical_alerts: alerts
                .iter()
                .filter(|a| a.severity == AlertSeverity::Critical)
                .count(),
        }
    }

    /// Set callback for alerts
    pub async fn set_alert_callback<F>(&self, callback: F)
    where
        F: Fn(WatchtowerAlert) + Send + Sync + 'static,
    {
        let mut cb = self.alert_callback.write().await;
        *cb = Some(Box::new(callback));
    }

    /// Internal: emit an alert
    async fn emit_alert(&self, alert: WatchtowerAlert) {
        // Store alert
        let mut alerts = self.alerts.write().await;
        alerts.push(alert.clone());
        drop(alerts);

        // Call callback if set
        let cb = self.alert_callback.read().await;
        if let Some(ref callback) = *cb {
            callback(alert);
        }
    }

    /// Hash a state update for comparison/verification
    fn hash_state(&self, state: &SignedStateUpdate) -> [u8; 32] {
        let mut hasher = Sha256::new();
        hasher.update(state.state.nonce.to_le_bytes());
        hasher.update(state.state.sender_balance.to_le_bytes());
        hasher.update(state.state.receiver_balance.to_le_bytes());
        hasher.finalize().into()
    }

    /// Get all monitored channels for iteration
    ///
    /// Returns a copy of the channels map for safe iteration
    /// while allowing other operations to proceed.
    pub async fn get_monitored_channels(&self) -> HashMap<String, WatchedChannel> {
        self.channels.read().await.clone()
    }
}

/// Statistics about watchtower operations
#[derive(Debug, Clone)]
pub struct WatchtowerStats {
    pub total_channels: usize,
    pub active_channels: usize,
    pub fraud_detected: usize,
    pub challenges_submitted: usize,
    pub total_fees_collected: u64,
    pub total_alerts: usize,
    pub critical_alerts: usize,
}

/// Background monitoring service
pub struct WatchtowerMonitor {
    watchtower: Arc<Watchtower>,
    /// Currency chain client for blockchain queries
    currency_chain: Arc<CurrencyChainClient>,
    /// Flag to stop the monitor
    running: Arc<RwLock<bool>>,
    /// Last processed block height for close events
    last_processed_block: Arc<RwLock<u64>>,
}

impl WatchtowerMonitor {
    /// Create a new monitor for the watchtower with currency chain client
    pub fn new(watchtower: Arc<Watchtower>, currency_chain: Arc<CurrencyChainClient>) -> Self {
        Self {
            watchtower,
            currency_chain,
            running: Arc::new(RwLock::new(false)),
            last_processed_block: Arc::new(RwLock::new(0)),
        }
    }

    /// Start the background monitoring loop
    pub async fn start(&self) {
        let mut running = self.running.write().await;
        *running = true;
        drop(running);

        let poll_interval = self.watchtower.config.poll_interval_secs;

        loop {
            // Check if we should stop
            let running = self.running.read().await;
            if !*running {
                break;
            }
            drop(running);

            // Check for expiring challenges
            self.watchtower.check_expiring_challenges().await;

            // Cleanup expired channels
            self.watchtower.cleanup_expired_channels().await;

            // Poll blockchain for unilateral close events and respond to fraud
            if let Err(e) = self.poll_close_events().await {
                tracing::warn!("Error polling close events: {}", e);
            }

            tokio::time::sleep(tokio::time::Duration::from_secs(poll_interval)).await;
        }
    }

    /// Poll the blockchain for unilateral close events
    async fn poll_close_events(&self) -> Result<(), WatchtowerError> {
        let last_block = *self.last_processed_block.read().await;

        // Get current block height from currency chain
        let current_block = self.get_current_block_height().await.ok_or_else(|| {
            WatchtowerError::InternalError(
                "Failed to get current block height from currency chain".to_string(),
            )
        })?;

        // Skip if no new blocks
        if current_block <= last_block {
            return Ok(());
        }

        tracing::debug!(
            "Watchtower polling blocks {} to {} for close events",
            last_block + 1,
            current_block
        );

        // Get monitored channels
        let channels = self.watchtower.get_monitored_channels().await;

        for (channel_id, channel_data) in channels {
            // Query blockchain for ChannelCloseInitiated events for this channel
            if let Some(close_event) = self
                .get_unilateral_close_event(&channel_id, last_block + 1, current_block)
                .await
            {
                tracing::info!(
                    "🔍 Watchtower detected unilateral close for channel {}: nonce={}, block={}",
                    channel_id,
                    close_event.submitted_nonce,
                    close_event.block_number
                );

                // Check if we have a newer state
                if let Some(latest_state) = &channel_data.latest_state {
                    if close_event.submitted_nonce < latest_state.latest_state.state.nonce {
                        // Fraud detected! Submit challenge
                        tracing::warn!(
                            "⚠️ FRAUD ATTEMPT detected on channel {}: submitted nonce {} < known nonce {}",
                            channel_id,
                            close_event.submitted_nonce,
                            latest_state.latest_state.state.nonce
                        );

                        // Create unilateral close request for challenge
                        let close_request = UnilateralCloseRequest {
                            channel_id: channel_id.clone(),
                            final_state: close_event.submitted_state.clone(),
                            initiator: close_event.initiator.clone(),
                            submitted_at: Utc::now(),
                            dispute_deadline: close_event.dispute_deadline,
                            challenged: false,
                            chain_tx_id: None,
                        };

                        // Respond to fraud with our newer state
                        if let Err(e) = self
                            .watchtower
                            .auto_respond_to_fraud(channel_id.clone(), &close_request)
                            .await
                        {
                            tracing::error!("Failed to respond to fraud: {}", e);
                        }
                    }
                }
            }
        }

        // Update last processed block
        let mut last = self.last_processed_block.write().await;
        *last = current_block;

        Ok(())
    }

    /// Get unilateral close event for a channel from the blockchain
    ///
    /// Queries the currency chain for ChannelCloseInitiated events
    /// filtered by channel_id and block range.
    async fn get_unilateral_close_event(
        &self,
        channel_id: &str,
        from_block: u64,
        to_block: u64,
    ) -> Option<UnilateralCloseEvent> {
        // Query the currency chain for ChannelCloseInitiated events
        let events = self
            .currency_chain
            .get_payment_channel_events("ChannelCloseInitiated", from_block, Some(to_block))
            .await
            .ok()?;

        // Find event matching our channel
        for event in events {
            if let Some(event_channel_id) = event.get("channel_id").and_then(|v| v.as_str()) {
                if event_channel_id == channel_id {
                    // Parse event data into UnilateralCloseEvent
                    let submitted_nonce = event.get("nonce").and_then(|v| v.as_u64()).unwrap_or(0);

                    let block_number = event
                        .get("block_number")
                        .and_then(|v| v.as_u64())
                        .unwrap_or(0);

                    let dispute_deadline_ts = event
                        .get("dispute_deadline")
                        .and_then(|v| v.as_i64())
                        .unwrap_or(0);
                    let dispute_deadline =
                        DateTime::from_timestamp(dispute_deadline_ts, 0).unwrap_or_else(Utc::now);

                    // Parse initiator
                    let initiator_str = event
                        .get("initiator")
                        .and_then(|v| v.as_str())
                        .unwrap_or("");
                    let initiator = if let Ok(uuid) = uuid::Uuid::parse_str(initiator_str) {
                        UserId(uuid)
                    } else {
                        UserId::new()
                    };

                    // Parse state balances
                    let sender_balance = event
                        .get("sender_balance")
                        .and_then(|v| v.as_u64())
                        .unwrap_or(0);
                    let receiver_balance = event
                        .get("receiver_balance")
                        .and_then(|v| v.as_u64())
                        .unwrap_or(0);

                    // Reconstruct the signed state from event data
                    let submitted_state = SignedStateUpdate {
                        state: crate::payment_channels::ChannelState {
                            nonce: submitted_nonce,
                            sender_balance,
                            receiver_balance,
                        },
                        sender_signature: event
                            .get("sender_signature")
                            .and_then(|v| v.as_str())
                            .map(|s| hex::decode(s).unwrap_or_default())
                            .unwrap_or_default(),
                        receiver_signature: event
                            .get("receiver_signature")
                            .and_then(|v| v.as_str())
                            .map(|s| hex::decode(s).unwrap_or_default()),
                        timestamp: Utc::now(),
                    };

                    return Some(UnilateralCloseEvent {
                        channel_id: channel_id.to_string(),
                        submitted_nonce,
                        submitted_state,
                        initiator,
                        block_number,
                        dispute_deadline,
                    });
                }
            }
        }

        None
    }

    /// Get current block height from the currency chain
    async fn get_current_block_height(&self) -> Option<u64> {
        self.currency_chain.get_current_height().await.ok()
    }

    /// Stop the monitoring loop
    pub async fn stop(&self) {
        let mut running = self.running.write().await;
        *running = false;
    }
}

/// Event data for a unilateral close detected on-chain
#[derive(Debug, Clone)]
pub struct UnilateralCloseEvent {
    /// Channel being closed
    pub channel_id: String,
    /// Nonce of the submitted state
    pub submitted_nonce: u64,
    /// The submitted state
    pub submitted_state: SignedStateUpdate,
    /// Who initiated the close
    pub initiator: UserId,
    /// Block number of the close event
    pub block_number: u64,
    /// When the dispute period ends
    pub dispute_deadline: DateTime<Utc>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::currency_chain::CurrencyChainConfig;

    #[test]
    fn test_watchtower_config_default() {
        let config = WatchtowerConfig::default();
        assert_eq!(config.min_monthly_fee, 1000);
        assert_eq!(config.max_channels, 10000);
        assert_eq!(config.poll_interval_secs, 30);
    }

    #[tokio::test]
    async fn test_watchtower_creation() {
        let channel_manager = Arc::new(PaymentChannelManager::new());
        let watchtower = Watchtower::new(WatchtowerConfig::default(), channel_manager);

        let stats = watchtower.get_statistics().await;
        assert_eq!(stats.total_channels, 0);
        assert_eq!(stats.active_channels, 0);
        assert_eq!(stats.fraud_detected, 0);
    }

    #[tokio::test]
    async fn test_watchtower_monitor_creation() {
        let channel_manager = Arc::new(PaymentChannelManager::new());
        let watchtower = Arc::new(Watchtower::new(
            WatchtowerConfig::default(),
            channel_manager,
        ));
        let currency_chain =
            Arc::new(CurrencyChainClient::new_mock(CurrencyChainConfig::default()));

        let _monitor = WatchtowerMonitor::new(watchtower, currency_chain);
        // Monitor created successfully with currency chain integration
    }
}
