//! Build-time helpers for DPL program compilation
//!
//! This module provides utilities for use in `build.rs` files to ensure
//! proper manifest generation and verification during the build process.
//!
//! # Usage in build.rs
//!
//! ```rust,ignore
//! // build.rs
//! use dchat_dpl::build::{BuildConfig, generate_manifest_metadata};
//!
//! fn main() {
//!     // Generate manifest metadata at build time
//!     generate_manifest_metadata(&BuildConfig::default());
//!     
//!     // Re-run if IDL changes
//!     println!("cargo:rerun-if-changed=idl.json");
//! }
//! ```
//!
//! # Reproducible Builds
//!
//! For reproducible builds, set these environment variables:
//!
//! - `DPL_BUILD_TIMESTAMP`: Fixed Unix timestamp (defaults to current time)
//! - `DPL_BUILD_HOST`: Build host identifier (defaults to hostname)
//! - `DPL_SCHEMA_HASH`: Pre-computed schema hash for verification
//! - `SOURCE_DATE_EPOCH`: Standard reproducible builds timestamp

use std::env;
use std::fs;
use std::path::PathBuf;

/// Build configuration for manifest generation
#[derive(Debug, Clone)]
pub struct BuildConfig {
    /// Path to IDL JSON file (optional, for schema hash verification)
    pub idl_path: Option<PathBuf>,
    /// Expected schema hash (32 bytes hex-encoded, for CI verification)
    pub expected_schema_hash: Option<String>,
    /// Path to output generated metadata
    pub out_dir: Option<PathBuf>,
    /// Enable verbose build output
    pub verbose: bool,
}

impl Default for BuildConfig {
    fn default() -> Self {
        Self {
            idl_path: None,
            expected_schema_hash: None,
            out_dir: env::var("OUT_DIR").ok().map(PathBuf::from),
            verbose: env::var("DPL_BUILD_VERBOSE").is_ok(),
        }
    }
}

/// Build error types
#[derive(Debug, Clone)]
pub enum BuildError {
    /// IDL file not found
    IdlNotFound(String),
    /// Schema hash mismatch
    SchemaMismatch { expected: String, actual: String },
    /// IO error
    IoError(String),
    /// Parse error
    ParseError(String),
}

impl std::fmt::Display for BuildError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            BuildError::IdlNotFound(path) => write!(f, "IDL file not found: {}", path),
            BuildError::SchemaMismatch { expected, actual } => {
                write!(
                    f,
                    "Schema hash mismatch!\n  Expected: {}\n  Actual: {}",
                    expected, actual
                )
            }
            BuildError::IoError(msg) => write!(f, "IO error: {}", msg),
            BuildError::ParseError(msg) => write!(f, "Parse error: {}", msg),
        }
    }
}

impl std::error::Error for BuildError {}

/// Result type for build operations
pub type BuildResult<T> = Result<T, BuildError>;

/// Generate manifest metadata at build time
///
/// This function:
/// 1. Reads build environment variables
/// 2. Generates version and build info constants
/// 3. Optionally verifies schema hash against expected value
/// 4. Writes metadata to OUT_DIR for inclusion via `include!`
///
/// # Panics
///
/// Panics with a clear error message if schema verification fails.
/// This ensures CI builds fail loudly on manifest mismatch.
pub fn generate_manifest_metadata(config: &BuildConfig) -> BuildResult<()> {
    let out_dir = config
        .out_dir
        .clone()
        .ok_or_else(|| BuildError::IoError("OUT_DIR not set".into()))?;

    // Get reproducible build timestamp
    let build_timestamp = get_build_timestamp();

    // Get build host (sanitized for reproducibility)
    let build_host = get_build_host();

    // Get git commit hash if available
    let git_commit = get_git_commit();

    // Get SDK version from Cargo.toml
    let sdk_version = env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "0.0.0".into());

    // Generate metadata source file
    let mut metadata = String::new();
    metadata.push_str("// Auto-generated by dchat-dpl build.rs\n");
    metadata.push_str("// Do not edit manually!\n\n");

    metadata.push_str(&format!(
        "pub const BUILD_TIMESTAMP: u64 = {};\n",
        build_timestamp
    ));
    metadata.push_str(&format!(
        "pub const BUILD_HOST: &str = \"{}\";\n",
        build_host
    ));
    metadata.push_str(&format!(
        "pub const SDK_VERSION: &str = \"{}\";\n",
        sdk_version
    ));

    if let Some(commit) = git_commit {
        metadata.push_str(&format!(
            "pub const GIT_COMMIT: Option<&str> = Some(\"{}\");\n",
            commit
        ));
    } else {
        metadata.push_str("pub const GIT_COMMIT: Option<&str> = None;\n");
    }

    // Verify schema hash if expected value provided
    if let (Some(idl_path), Some(expected_hash)) = (&config.idl_path, &config.expected_schema_hash)
    {
        let actual_hash = compute_idl_schema_hash(idl_path)?;
        let actual_hex = hex::encode(&actual_hash);

        if actual_hex != *expected_hash {
            let err = BuildError::SchemaMismatch {
                expected: expected_hash.clone(),
                actual: actual_hex,
            };
            // Panic for CI visibility
            panic!("{}", err);
        }

        metadata.push_str(&format!(
            "pub const VERIFIED_SCHEMA_HASH: [u8; 32] = {:?};\n",
            actual_hash
        ));

        if config.verbose {
            println!("cargo:warning=DPL: Schema hash verified: {}", expected_hash);
        }
    }

    // Write metadata file
    let metadata_path = out_dir.join("dpl_build_metadata.rs");
    fs::write(&metadata_path, metadata)
        .map_err(|e| BuildError::IoError(format!("Failed to write metadata: {}", e)))?;

    // Print cargo directives
    if let Some(idl_path) = &config.idl_path {
        println!("cargo:rerun-if-changed={}", idl_path.display());
    }
    println!("cargo:rerun-if-env-changed=DPL_BUILD_TIMESTAMP");
    println!("cargo:rerun-if-env-changed=DPL_SCHEMA_HASH");
    println!("cargo:rerun-if-env-changed=SOURCE_DATE_EPOCH");

    Ok(())
}

/// Compute schema hash from IDL JSON file
pub fn compute_idl_schema_hash(idl_path: &PathBuf) -> BuildResult<[u8; 32]> {
    let idl_json = fs::read_to_string(idl_path)
        .map_err(|e| BuildError::IdlNotFound(format!("{}: {}", idl_path.display(), e)))?;

    // Parse and re-serialize to canonical form
    let idl: crate::idl::Idl = serde_json::from_str(&idl_json)
        .map_err(|e| BuildError::ParseError(format!("Invalid IDL JSON: {}", e)))?;

    Ok(idl.schema_hash())
}

/// Get build timestamp for reproducibility
fn get_build_timestamp() -> u64 {
    // Priority:
    // 1. DPL_BUILD_TIMESTAMP env var
    // 2. SOURCE_DATE_EPOCH (standard reproducible builds)
    // 3. Current time

    if let Ok(ts) = env::var("DPL_BUILD_TIMESTAMP") {
        if let Ok(parsed) = ts.parse::<u64>() {
            return parsed;
        }
    }

    if let Ok(ts) = env::var("SOURCE_DATE_EPOCH") {
        if let Ok(parsed) = ts.parse::<u64>() {
            return parsed;
        }
    }

    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

/// Get build host identifier (sanitized for reproducibility)
fn get_build_host() -> String {
    if let Ok(host) = env::var("DPL_BUILD_HOST") {
        return host;
    }

    // Use target triple as reproducible identifier
    env::var("TARGET").unwrap_or_else(|_| "unknown".into())
}

/// Get git commit hash if in a git repository
fn get_git_commit() -> Option<String> {
    // Try reading from GIT_COMMIT env var first
    if let Ok(commit) = env::var("GIT_COMMIT") {
        if commit.len() >= 7 {
            return Some(commit[..7].to_string());
        }
    }

    // Try running git command
    std::process::Command::new("git")
        .args(["rev-parse", "--short=7", "HEAD"])
        .output()
        .ok()
        .and_then(|output| {
            if output.status.success() {
                String::from_utf8(output.stdout)
                    .ok()
                    .map(|s| s.trim().to_string())
            } else {
                None
            }
        })
}

/// Verify that a compiled WASM file has the expected manifest
///
/// Use this in integration tests or CI to verify the build output.
pub fn verify_wasm_manifest(
    wasm_path: &PathBuf,
    expected_schema_hash: &[u8; 32],
) -> BuildResult<()> {
    let wasm_bytes = fs::read(wasm_path)
        .map_err(|e| BuildError::IoError(format!("Failed to read WASM: {}", e)))?;

    // Use the manifest extraction from dchat-programs
    // Note: This requires the dchat-programs crate to be available
    let manifest = extract_manifest_from_wasm(&wasm_bytes)?;

    if &manifest.schema_hash != expected_schema_hash {
        return Err(BuildError::SchemaMismatch {
            expected: hex::encode(expected_schema_hash),
            actual: hex::encode(&manifest.schema_hash),
        });
    }

    Ok(())
}

/// Extract manifest from WASM bytecode (simplified version for build script use)
fn extract_manifest_from_wasm(bytecode: &[u8]) -> BuildResult<ManifestInfo> {
    // Minimal WASM parsing for build script use
    if bytecode.len() < 8 {
        return Err(BuildError::ParseError("WASM too short".into()));
    }

    if &bytecode[0..4] != &[0x00, 0x61, 0x73, 0x6d] {
        return Err(BuildError::ParseError("Invalid WASM magic".into()));
    }

    // Parse sections looking for dpl_manifest custom section
    let mut offset = 8;

    while offset < bytecode.len() {
        let section_id = bytecode[offset];
        offset += 1;

        let (section_size, bytes_read) = read_leb128(&bytecode[offset..])
            .map_err(|e| BuildError::ParseError(format!("LEB128 error: {}", e)))?;
        offset += bytes_read;

        if section_id == 0 {
            // Custom section
            let section_start = offset;
            let (name_len, name_bytes_read) = read_leb128(&bytecode[offset..])
                .map_err(|e| BuildError::ParseError(format!("LEB128 error: {}", e)))?;
            offset += name_bytes_read;

            if offset + name_len > bytecode.len() {
                return Err(BuildError::ParseError("Section name overflow".into()));
            }

            let name = &bytecode[offset..offset + name_len];
            offset += name_len;

            if name == b"dpl_manifest" {
                let data_len = section_size - (offset - section_start);
                if data_len != 64 {
                    return Err(BuildError::ParseError(format!(
                        "Invalid manifest size: {} (expected 64)",
                        data_len
                    )));
                }

                if &bytecode[offset..offset + 4] != &[0x44, 0x50, 0x4C, 0x4D] {
                    return Err(BuildError::ParseError("Invalid manifest magic".into()));
                }

                let mut schema_hash = [0u8; 32];
                schema_hash.copy_from_slice(&bytecode[offset + 16..offset + 48]);

                return Ok(ManifestInfo { schema_hash });
            }
        }

        offset += section_size;
    }

    Err(BuildError::ParseError(
        "DPL manifest section not found".into(),
    ))
}

/// Simplified manifest info for build verification
#[derive(Debug, Clone)]
pub struct ManifestInfo {
    pub schema_hash: [u8; 32],
}

/// Read a LEB128-encoded u32
fn read_leb128(data: &[u8]) -> Result<(usize, usize), &'static str> {
    let mut result: usize = 0;
    let mut shift = 0;
    let mut bytes_read = 0;

    for byte in data.iter().take(5) {
        bytes_read += 1;
        result |= ((byte & 0x7F) as usize) << shift;
        if byte & 0x80 == 0 {
            return Ok((result, bytes_read));
        }
        shift += 7;
    }

    Err("LEB128 overflow")
}

/// CLI tool for manifest verification (can be run as standalone binary)
#[allow(dead_code)]
pub fn cli_main() {
    use std::process;

    let args: Vec<String> = env::args().collect();

    if args.len() < 2 {
        eprintln!("Usage: {} <command> [args...]", args[0]);
        eprintln!();
        eprintln!("Commands:");
        eprintln!("  verify-schema <idl.json> <expected_hash>  Verify IDL schema hash");
        eprintln!("  verify-wasm <file.wasm> <expected_hash>   Verify WASM manifest");
        eprintln!("  extract <file.wasm>                       Extract and print manifest");
        process::exit(1);
    }

    match args[1].as_str() {
        "verify-schema" => {
            if args.len() < 4 {
                eprintln!(
                    "Usage: {} verify-schema <idl.json> <expected_hash>",
                    args[0]
                );
                process::exit(1);
            }

            let idl_path = PathBuf::from(&args[2]);
            let expected = &args[3];

            match compute_idl_schema_hash(&idl_path) {
                Ok(hash) => {
                    let actual = hex::encode(&hash);
                    if actual == *expected {
                        println!("✓ Schema hash verified: {}", actual);
                        process::exit(0);
                    } else {
                        eprintln!("✗ Schema hash mismatch!");
                        eprintln!("  Expected: {}", expected);
                        eprintln!("  Actual:   {}", actual);
                        process::exit(1);
                    }
                }
                Err(e) => {
                    eprintln!("Error: {}", e);
                    process::exit(1);
                }
            }
        }

        "verify-wasm" => {
            if args.len() < 4 {
                eprintln!("Usage: {} verify-wasm <file.wasm> <expected_hash>", args[0]);
                process::exit(1);
            }

            let wasm_path = PathBuf::from(&args[2]);
            let expected = &args[3];

            let expected_bytes: [u8; 32] = match hex::decode(expected) {
                Ok(v) if v.len() == 32 => v.try_into().unwrap(),
                _ => {
                    eprintln!("Invalid expected hash: must be 64 hex characters");
                    process::exit(1);
                }
            };

            match verify_wasm_manifest(&wasm_path, &expected_bytes) {
                Ok(()) => {
                    println!("✓ WASM manifest verified");
                    process::exit(0);
                }
                Err(e) => {
                    eprintln!("✗ Verification failed: {}", e);
                    process::exit(1);
                }
            }
        }

        "extract" => {
            if args.len() < 3 {
                eprintln!("Usage: {} extract <file.wasm>", args[0]);
                process::exit(1);
            }

            let wasm_path = PathBuf::from(&args[2]);
            let wasm_bytes = match fs::read(&wasm_path) {
                Ok(bytes) => bytes,
                Err(e) => {
                    eprintln!("Failed to read WASM file: {}", e);
                    process::exit(1);
                }
            };

            match extract_manifest_from_wasm(&wasm_bytes) {
                Ok(manifest) => {
                    println!("Schema hash: {}", hex::encode(&manifest.schema_hash));
                    process::exit(0);
                }
                Err(e) => {
                    eprintln!("Failed to extract manifest: {}", e);
                    process::exit(1);
                }
            }
        }

        _ => {
            eprintln!("Unknown command: {}", args[1]);
            process::exit(1);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_leb128_parsing() {
        // Single byte
        assert_eq!(read_leb128(&[0x00]).unwrap(), (0, 1));
        assert_eq!(read_leb128(&[0x7F]).unwrap(), (127, 1));

        // Multi-byte
        assert_eq!(read_leb128(&[0x80, 0x01]).unwrap(), (128, 2));
        assert_eq!(read_leb128(&[0xE5, 0x8E, 0x26]).unwrap(), (624485, 3));
    }

    #[test]
    fn test_build_timestamp_env() {
        env::set_var("DPL_BUILD_TIMESTAMP", "1234567890");
        let ts = get_build_timestamp();
        assert_eq!(ts, 1234567890);
        env::remove_var("DPL_BUILD_TIMESTAMP");
    }

    #[test]
    fn test_build_config_default() {
        let config = BuildConfig::default();
        assert!(config.idl_path.is_none());
        assert!(config.expected_schema_hash.is_none());
    }
}
